deeeed/expo-audio-stream

packages/expo-audio-stream/ios/AudioStreamManager.swift
Setting this option allows microphone input from Bluetooth devices (such as Airpods). Tested locally by editing build files in XCode.
[Apple Documentation](https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions/1616518-allowbluetooth)
=> Add support for recording from Bluetooth devices

packages/expo-audio-stream/src/workers/InlineFeaturesExtractor.web.tsx
During medium/long sessions this made it hard to read other console logs.
=> Remove frequently-firing log line

documentation_site/docs/hooks/use-audio-recorder.md, packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/src/AudioRecorder.provider.tsx, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/ExpoAudioStream.web.ts, packages/expo-audio-stream/src/useAudioRecorder.tsx
There is a small bug where pausing/resuming a recording causes issues since the internal state of web/ios does not set the `(this).isPaused = false`.
I also fixed the types of `pauseRecording` and `resumeRecording` since those are async functions and useful in application logic for waiting until the pause/resume is finished
=> fix(expo-audio-stream): bug in pause logic and types for pauseRecording/resumeRecording

documentation_site/docusaurus.config.ts
The header linked to your old GitHub account rather than the current one 😄
=> fixed link in header of docs site

packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/Constants.kt
Going off of #31, this allows applications to set the audio interval to 10ms. I tested it at 20ms without issues, so I put it at 10ms to enable other devs to experiment.
=> updated min interval on android to 10ms (from 100ms)

packages/expo-audio-stream/ios/AudioStreamManager.swift
Fixes https://github.com/deeeed/expo-audio-stream/issues/35
=> Return actual recording settings from startRecording on iOS

apps/playground/src/AppRoot.tsx, apps/playground/src/app/(tabs)/record.tsx, apps/playground/src/component/IOSSettingsConfig.tsx, apps/playground/src/component/IOSSettingsConfigForm.tsx, packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/ios/RecordingSettings.swift, packages/expo-audio-stream/src/ExpoAudioStream.types.ts
This PR introduces comprehensive iOS audio session configuration capabilities, allowing fine-grained control over audio behavior in iOS devices. The implementation enables developers to customize audio categories, modes, and category options through a new user interface in the playground app.
- Added new iOS audio session configuration types and interfaces
- Implemented configuration UI components with form controls
- Enhanced Swift implementation to handle custom audio session settings
- Added detailed logging for audio session configuration
- Set sensible defaults while maintaining backward compatibility
- `IOSSettingsConfig`: Main configuration component with edit capabilities
- `IOSSettingsConfigForm`: Form component for audio session settings with:
- Audio category selection …
=> feat(expo-audio-stream): add comprehensive ios audio session configuration support

packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt
Fixes issues with audio recording state management across platforms:
- iOS: Initial position carries over from previous recordings
- Android: Total size counter not resetting between recordings
- iOS: Reset `lastEmittedSize` when starting new recording
- Android: Reset `totalDataSize` when initializing new recording file
No breaking changes or migration steps required.
=> fix: reset audio recording state properly on iOS and Android

documentation_site/docs/api-reference/recording-config.md, packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift
This PR addresses two key issues in the iOS audio implementation:
1. Improves handling of custom sampling rates through proper resampling (fixes #62)
2. Fixes duration calculation bugs during pause/resume operations
- Implemented high-quality resampling using `AVAudioConverter` to properly handle requested sampling rates
- Added intermediate Float32 format processing for better quality preservation
- Improved hardware sample rate detection and fallback behavior
- Enhanced logging for debugging sample rate issues
- Fixed duration calculation when pausing/resuming multiple times
- Replaced `pausedDuration` with more accurate `totalPausedDuration` tracking
- Added `currentPauseStart` to properly handle pause states
- Updated duration calculations to be based on actual audio data size
- Uses …
=> fix(ios): improve audio resampling and duration tracking

packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioNotificationsManager.kt
The audio recording notification was incorrectly triggering multiple alerts when updating its content (e.g., recording duration updates). This caused unnecessary notification alerts throughout the recording session, affecting both the device and any connected accessories.
Modified the notification configuration to properly update the existing notification instead of triggering new alerts:
```diff
- .clearActions()
+ .setOnlyAlertOnce(true)
+ .setOngoing(true)
```
These minimal changes ensure:
- Only one notification alert occurs when recording starts
- Subsequent notification updates happen silently
- The notification properly indicates its ongoing status
- `setOnlyAlertOnce(true)`: Ensures notification updates don't trigger new alerts
- `setOngoing(true)`: Indicates this is a continuous …
=> fix: prevent duplicate notifications during audio recording on Android

packages/expo-audio-stream/src/ExpoAudioStream.web.ts, packages/expo-audio-stream/src/WebRecorder.web.ts
This PR addresses an issue where audio recordings on the web platform were not being processed correctly due to improper WAV header handling.
The web implementation was incorrectly handling WAV headers during audio processing:
- WAV headers were being written at the wrong stage of the processing pipeline
- PCM data was not being properly combined with WAV headers
- Memory leaks due to uncleaned object URLs
The implementation has been improved by:
1. Streamlining WAV header creation and PCM data combination into a single step
2. Ensuring WAV headers are written at the correct processing stage
3. Adding proper cleanup of object URLs to prevent memory leaks
4. Using proper MIME types for audio blobs
- Modified `ExpoAudioStream.web.ts` to combine WAV header creation with PCM data in one step …
=> fix(expo-audio-stream): correct WAV audio processing on web platform

apps/playground/public/audioworklet.js, apps/playground/src/app/(recordings)/[filename].tsx, apps/playground/src/app/(tabs)/play.tsx, apps/playground/src/app/(tabs)/record.tsx, apps/playground/src/component/AudioRecordingView.tsx, documentation_site/docs/api-reference/audio-recording.md, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/ExpoAudioStream.web.ts, packages/expo-audio-stream/src/WebRecorder.web.ts, packages/expo-audio-stream/src/useAudioRecorder.tsx, packages/expo-audio-stream/src/workers/inlineAudioWebWorker.web.tsx
This PR significantly improves the web audio recording implementation by optimizing memory usage and introducing a streaming-first approach. The changes focus on reducing memory footprint for long recordings while maintaining compatibility with existing features.
- Replaced storing complete audio history with a sliding window approach
- Implemented chunk-based processing in the AudioWorklet
- Added configurable buffer size limits to prevent memory growth
- Set default maximum audio buffer length to 5 seconds at 48kHz
- Moved from batch processing to real-time streaming of audio data
- Simplified AudioWorklet processor by removing redundant buffer storage
- Improved error handling and cleanup processes
- Added performance monitoring and logging
- Web implementation no longer returns full …
=> feat(web-audio): optimize memory usage and streaming performance for web audio recording

packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioNotificationsManager.kt
This PR prevents duplicate notification alerts and constant vibrations on wearable devices by modifying notification settings in AudioNotificationsManager.
- Added `setOnlyAlertOnce(true)` to prevent duplicate alerts
- Disabled vibration with `setVibrate(null)`
- Reset notification defaults with `setDefaults(0)`
- Set `setLocalOnly(true)` to limit notifications to the local device
Improves user experience by:
- Preventing wearable devices from constantly vibrating
- Reducing notification fatigue
- Maintaining audio stream status visibility without disruption
No breaking changes or migration steps required.
=> feat: disable duplicate notification alerts for audio stream

apps/playground/src/AppRoot.tsx, documentation_site/docs/installation.md, packages/expo-audio-stream/plugin/src/index.ts
Fixes #85 - Apps using expo-audio-stream are getting rejected from the App Store due to automatic inclusion of VoIP and audio background modes, even when these modes aren't required for the app's functionality.
The plugin was automatically adding VoIP and audio background modes to support background recording, but this approach conflicts with App Store guidelines which require these modes to be used only for their intended purposes:
- VoIP mode should only be used for actual Voice-over-IP functionality
- Audio background mode should only be used for audio playback, not recording
This PR modifies the plugin to:
1. Disable VoIP and audio background modes by default
2. Use background processing mode as the default mechanism for background recording
3. Add explicit configuration options for …
=> fix(plugin): remove automatic VoIP and audio background modes for iOS

apps/playground/src/app/(tabs)/record.tsx, apps/playground/src/component/IOSSettingsConfig.tsx, apps/playground/src/component/NativeNotificationConfig.tsx, apps/playground/src/context/AudioFilesProvider.tsx, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/RecordingConfig.kt, packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/ios/RecordingSettings.swift, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/ExpoAudioStream.web.ts, packages/expo-audio-stream/src/WebRecorder.web.ts
This PR adds the ability to specify custom filenames and output directories for audio recordings across all platforms (iOS, Android, and Web). The implementation includes proper validation of paths, error handling, and consistent behavior across platforms.
- Added `filename` and `outputDirectory` options to `RecordingConfig`
- Implemented custom filename support across all platforms (iOS, Android, Web)
- Added directory validation and error handling
- Improved file path handling and cleaning
- Added UI for custom filename input in the playground app
- Added storage location info display for native platforms
- **Custom Filename Support**: Users can now specify custom filenames for recordings
- Automatically appends `.wav` extension if missing
- Falls back to UUID/timestamp if no filename …
=> feat: add custom filename and directory support for audio recordings

packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/ios/AudioStreamManagerDelegate.swift, packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift
This PR implements call state validation and fixes recording state inconsistencies when interacting with phone calls on both Android and iOS platforms.
- #88: Resume recording during phone call leads to invalid state
- #89: Recording state inconsistency after call ends
Two issues were identified with the current audio recording implementation:
1. Recording could be resumed during an active phone call, leading to an invalid state
2. Recording state (isPaused) becomes inconsistent after a call ends, not properly reflecting the actual recording status
The changes implement proper call state validation and handling:
- Added call state check using `TelephonyManager` before allowing recording to resume
- Prevents recording from resuming during active calls by rejecting the promise with a …
=> fix: prevent audio recording during active calls and fix recording state management

packages/expo-audio-ui/src/DecibelGauge/DecibelGauge.stories.tsx, packages/expo-audio-ui/src/DecibelGauge/DecibelGauge.tsx, packages/expo-audio-ui/src/DecibelMeter/DecibelMeter.stories.tsx, packages/expo-audio-ui/src/DecibelMeter/DecibelMeter.tsx
This PR introduces two new visualization components to the expo-audio-ui package: DecibelGauge and DecibelMeter. These components provide flexible and customizable ways to display audio decibel levels in React Native applications.
- Circular gauge visualization for decibel levels
- Customizable theming including colors, sizes, and stroke widths
- Animated transitions between decibel values
- Optional value display
- Support for different size variants (small, medium, large)
- Built with @shopify/react-native-skia for smooth rendering
- Linear meter visualization for decibel levels
- Supports both vertical and horizontal orientations
- Customizable ruler with tick marks and labels
- Color gradients based on decibel ranges
- Configurable min/max decibel ranges
- Themeable appearance
- Built …
=> feat(expo-audio-ui): Add DecibelGauge and DecibelMeter components

documentation_site/docs/api-reference/API/interfaces/RecordingConfig.md, packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/src/ExpoAudioStream.types.ts
This PR fixes an issue where Opus compression support was accidentally removed from iOS implementation. It also corrects documentation that incorrectly listed MP3 as a supported format.
- Restored Opus compression capability in iOS audio recording
- Corrected documentation to accurately reflect supported formats (AAC and Opus only)
- Added proper bit depth configuration for compressed recording
- Re-implemented Opus format support in `AudioStreamManager.swift`
- Updated compression settings to properly handle Opus format selection
- Added missing bit depth configuration in compressed recording settings
- Enhanced error handling for recorder initialization
- Fixed iOS implementation to properly support Opus compression that was accidentally removed
- Corrected documentation that …
=> fix: restore Opus compression support on iOS

packages/expo-audio-stream/src/ExpoAudioStreamModule.ts
Implementation of the web permission for microphone. Based on expo-audio packages. Fix #130
=> feat: add web permission for microphone

apps/playground/src/app/trim.tsx, apps/playground/src/components/TrimVisualization.tsx, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/ExpoAudioStreamModule.ts, packages/expo-audio-stream/src/trimAudio.ts
This pull request introduces significant enhancements to the `@siteed/expo-audio-stream` package and its playground app by:
1. Adding customizable output sample rate control (16kHz, 44.1kHz, 48kHz) for audio trimming
2. Implementing full audio trimming support on web platforms
3. Improving the trimming visualization UI
4. Enhancing format compatibility handling with better web-specific considerations
These changes improve audio processing flexibility, extend platform support, and provide a better user experience for developers working with audio trimming features.
- Added `SampleRate` type and integrated it into `TrimAudioOptions.outputFormat`
- Implemented UI controls in `TrimScreen` with a segmented button for sample rate selection (16kHz, 44.1kHz, 48kHz)
- Updated trimming logic to …
=> feat: Add Sample Rate Control and Web Trimming Support to Expo Audio Stream

documentation_site/docs/api-reference/recording-config.md, documentation_site/docs/hooks/use-audio-recorder.md, documentation_site/docs/installation.md, packages/expo-audio-studio/android/src/main/AndroidManifest.xml, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-studio/plugin/src/index.ts
This PR fixes issues with Android requesting "manage phone calls" permissions even when configured not to. It properly implements the `enablePhoneStateHandling` option to correctly respect the configuration and enhances documentation across installation guides and API reference pages to clarify how this feature works.
- Fixes [[#162](https://github.com/siteed/expo-audio-studio/issues/162)](https://github.com/siteed/expo-audio-studio/issues/162): Android requesting manage call permissions
- Fixes [[#185](https://github.com/siteed/expo-audio-studio/issues/185)](https://github.com/siteed/expo-audio-studio/issues/185): Permission still requested despite disabling phone state handling
- **Fix bug:** Ensure `enablePhoneStateHandling: false` actually prevents requesting phone permissions on …
=> fix: make phone call permissions optional and properly respect configuration

packages/expo-audio-studio/ios/AudioProcessor.swift, packages/expo-audio-studio/ios/AudioStreamManager.swift, packages/expo-audio-studio/ios/ExpoAudioStreamModule.swift
This PR introduces named constants for previously hardcoded values in the iOS audio processing modules, improving code readability, maintainability, and consistency. It also fixes an issue where the WAV header was included in audio analysis, causing false detection of audio activity at the start of recordings.
- Added `SILENCE_THRESHOLD_RMS` constant (0.01) in AudioProcessor.swift
- Added `WAV_HEADER_SIZE` constant (44 bytes) in AudioStreamManager.swift
- Added `DEFAULT_SEGMENT_DURATION_MS` constant (100) in ExpoAudioStreamModule.swift
- Modified AudioStreamManager to strip WAV header from first buffer before analysis
- Replaced all hardcoded instances with respective constants
- Updated related logic to maintain consistent behavior
This PR also addresses issue #168: "iOS: When starting …
=> refactor(audio-studio): introduce constants for silence threshold and WAV header size

apps/playground/package.json, packages/expo-audio-studio/package.json, packages/expo-audio-studio/react-native.config.js, packages/expo-audio-studio/src/utils/crc32.native.ts, packages/expo-audio-studio/src/utils/crc32.ts, packages/expo-audio-studio/src/utils/crc32.web.ts, yarn.lock
This PR replaces the external `crc-32` npm package with a native implementation, reducing our dependency footprint and improving bundle size across all platforms.
Previously, our codebase relied on the `crc-32` npm package for checksum calculations, which:
- Added an unnecessary external dependency
- Required platform-specific handling (web vs. native) 
- Created additional complexity in package configuration
This PR:
- Implements a custom CRC32 algorithm directly in TypeScript
- Uses a single source file with platform detection instead of separate `.web.ts` and `.native.ts` files
- Removes all references to the external `crc-32` package from dependencies and configuration
- Created an efficient CRC32 implementation that matches the behavior of the removed library
- Used a lazy …
=> feat: Implement native CRC32 calculation to remove external dependencies

apps/playground/package.json, documentation_site/docs/api-reference/recording-config.md, packages/expo-audio-studio/ios/AudioStreamManager.swift
This pull request addresses critical issues related to audio recording on iOS devices and simulators, specifically targeting the sample rate mismatch problem reported in issues #192 and #189. The changes ensure that the `expo-audio-stream` library can reliably handle audio recording by automatically detecting and adapting to the hardware's actual sample rate, preventing crashes due to mismatched sample rates (e.g., when the iOS simulator or device does not honor the requested sample rate). Additionally, this PR improves the developer experience by adding detailed logging for sample rate detection and updating the documentation to reflect the new behavior.
The key impacts of these changes are:
- **Improved Stability**: Eliminates crashes caused by sample rate mismatches, particularly on …
=> fix(audio-stream): resolve iOS sample rate mismatch and enhance recording stability

documentation_site/docs/installation.md, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/PermissionUtils.kt
This pull request introduces enhanced background audio handling and improved permission management for the Expo Audio Stream module. The changes aim to provide better control over audio recording in background scenarios while maintaining compatibility with Android's evolving permission requirements, particularly for Android 14+.
- Fixes #199 
- **Background Audio Support**: Adds a new `enableBackgroundAudio` flag to explicitly enable or disable background audio recording capabilities.
- **Permission Flexibility**: Updates permission checks to conditionally require `FOREGROUND_SERVICE_MICROPHONE` permission only when background audio is enabled, improving compatibility and reducing unnecessary permission requests.
- **Debugging Clarity**: Enhances logging around permission checks to …
=> feat(audio-stream): enhance background audio handling and permission checks

packages/expo-audio-studio/ios/AudioStreamManager.swift, yarn.lock
This pull request addresses issues where the final buffer of audio data was not emitted when stopping or pausing recordings on iOS, resolving issues #212 and #204. Additionally, it includes a minor lockfile update to maintain dependency consistency.
- Fixes #212 
- Fixes #204 
The primary change ensures that all recorded audio data, including the final buffer (typically 960 bytes), is emitted when a recording is stopped or paused. Previously, if the accumulated data hadn't reached the emission interval threshold, it was discarded, leading to incomplete recordings. This fix guarantees complete audio capture, improving the reliability of the recording feature in the expo-audio-studio package for iOS users.
- **AudioStreamManager.swift**:
- Modified `pauseRecording` and `stopRecording` …
=> fix(ios): ensure complete audio data emission on recording stop/pause

.github/ISSUE_TEMPLATE/bug_report.md, README.md, apps/playground/CHANGELOG.md, apps/playground/PUBLISH_STORE.md, apps/playground/README.md, apps/playground/app.config.ts, apps/playground/package.json, apps/playground/src/app/(tabs)/more.tsx, apps/playground/src/app/_layout.tsx, apps/playground/src/app/decibel.tsx, apps/playground/src/app/download.tsx, apps/playground/src/app/permissions.tsx, apps/playground/src/app/preview.tsx, apps/playground/src/app/trim.tsx, apps/playground/src/components/WebAppBanner.tsx, documentation_site/docs/playground.md, packages/expo-audio-studio/README.md
This PR rebrands the project from `expo-audio-stream` to `expo-audio-studio` and improves app discoverability with download links and promotional components.
**Purpose and Impact**:
- Updates project name to `expo-audio-studio` across documentation and issue templates.
- Adds App Store and Google Play download links in READMEs and documentation.
- Introduces `DownloadPage` and `WebAppBanner` components to promote app downloads.
- Enhances bug report template with cross-platform validation steps.
**Key Changes**:
- Updated READMEs with app store badges and web demo links.
- Revised `.github/ISSUE_TEMPLATE/bug_report.md` for `expo-audio-studio` and added platform testing guidance.
- Added `apps/playground/src/app/download.tsx` for a dedicated download page.
- Implemented …
=> feat: Update AudioPlayground branding and enhance app distribution

documentation_site/docs/api-reference/recording-config.md, packages/expo-audio-studio/android/src/androidTest/java/net/siteed/audiostream/integration/EventEmissionIntervalTest.kt, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/RecordingConfig.kt, packages/expo-audio-studio/ios/AudioStreamManager.swift, packages/expo-audio-studio/ios/ExpoAudioStudioTests/EventEmissionIntervalTests.swift, packages/expo-audio-studio/src/ExpoAudioStream.types.ts
This PR enforces a consistent 10ms minimum interval for event emissions across both iOS and Android platforms.
- iOS had a hardcoded 100ms minimum interval, preventing high-frequency updates needed for real-time audio visualizations
- Android defined a `MIN_INTERVAL` constant of 10ms but wasn't enforcing it
- Users couldn't achieve smooth, responsive audio visualizations due to the iOS limitation
- Reduced iOS minimum interval from 100ms to 10ms
- Added enforcement of the 10ms minimum on Android for consistency
- Both platforms now support intervals down to 10ms for high-frequency audio data updates
- **iOS** (`AudioStreamManager.swift`): Changed minimum from 100ms to 10ms
- **Android** (`RecordingConfig.kt`): Now enforces `MIN_INTERVAL` constant (10ms)
- Added Android integration test …
=> fix(expo-audio-studio): remove hardcoded 100ms interval limit on iOS

packages/expo-audio-studio/android/src/androidTest/java/net/siteed/audiostream/integration/PcmStreamingDurationTest.kt, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-studio/ios/AudioStreamManager.swift
This PR resolves Issue #263 where negative durations were returned in streaming-only mode due to incorrect file size-based calculations.
When primary output was disabled (streaming-only mode), the duration calculation relied on file size (0 bytes) minus WAV header (44 bytes), resulting in negative durations (-44ms typically).
The existing duration calculation logic in `AudioRecorderManager.kt` (lines 988-1011) always used file size-based calculations, even when no file was created in streaming-only mode.
- **Conditional duration calculation**: Use actual recording time for streaming-only mode, file size for file-based recording
- **Actual recording time calculation**: `System.currentTimeMillis() - recordingStartTime - pausedDuration`
- **Maintain backward compatibility**: File-based …
=> fix(android): resolve PCM streaming duration calculation bug (Issue #263)
