packages/expo-audio-ui/src/AudioVisualizer/CanvasContainer.tsx, packages/expo-audio-ui/src/RecordButton/RecordButton.stories.tsx, packages/expo-audio-ui/src/RecordButton/RecordButton.tsx, packages/expo-audio-ui/src/Waveform/Waveform.stories.tsx, packages/expo-audio-ui/src/Waveform/Waveform.tsx, packages/expo-audio-ui/src/index.ts
This PR introduces significant enhancements to the audio UI components, improving visualization capabilities and adding recording functionality.
- Added smooth curve rendering option using cubic bezier interpolation
- Introduced customizable theming support with color, stroke width, and opacity
- Improved performance through optimized path calculations
- Added new story variations showcasing different waveform styles
- Simplified component API by consolidating theme properties
- Implemented an animated recording button with multiple states (idle, recording, processing)
- Added pulse animation effect during recording state
- Included comprehensive styling options through props
- Created interactive stories demonstrating various states and customizations
- Supports customizable sizes, …
=> feat(expo-audio-ui): enhance Waveform component and add RecordButton

packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt
This PR addresses issue #38 where the `onAudioStream` callback was not being fired correctly on Android when stopping audio recording, particularly in paused state.
Two specific scenarios were identified where the final audio data chunk was not being properly handled:
1. When `stopRecording()` is executed, the last chunk of data was being lost
2. When stopping audio recording while in a paused state, the callback was not being executed
The implementation now:
- Properly handles the paused state by checking and reading any remaining data before stopping
- Ensures thread synchronization by joining the recording thread before final reads
- Uses `copyOfRange` to emit exactly the number of bytes read, preventing zero-padding
- Sets the recording state to false before final cleanup to prevent …
=> fix: handle final audio chunk during stopRecording on Android

apps/playground/src/app/(tabs)/record.tsx, apps/playground/src/component/IOSSettingsConfig.tsx, apps/playground/src/component/NativeNotificationConfig.tsx, apps/playground/src/hooks/useLiveTranscriber.ts, apps/playground/src/hooks/useReanimatedWebHack.ts
This PR enhances web platform support and improves error handling across several components, particularly focusing on audio recording and transcription functionality.
1. **Web Platform Audio Support**
- Added web-specific sample rate configuration (44.1kHz)
- Improved error handling for audio file storage on web platform
- Enhanced logging for debugging audio storage issues
2. **Live Transcriber Improvements**
- Added null safety checks for transcription chunks
- Fixed potential array access issues in transcript processing
- Improved buffer index management for incomplete transcriptions
3. **Code Cleanup**
- Removed unnecessary toast notification from Reanimated web hack
- Disabled default live transcription on web platform
- Enhanced error logging with detailed stack traces
=> fix: improve web platform stability and error handling

packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecordingService.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt
This PR addresses resource leaks in the Android audio recording module when the app is forcefully terminated. The changes ensure proper cleanup of audio resources and notification services.
- Added detection and cleanup of orphaned recording services
- Implemented proper resource cleanup in `onTaskRemoved`
- Added service status verification in status checks
- Introduced new `checkRecordingStatus` function
- Added complete cleanup sequence for audio resources
- Audio recording resources (AudioRecord, compressed recorder) are now properly released
- Notification services are cleaned up on app termination
- WAV header is updated before cleanup
- Added synchronization for thread safety during cleanup
- Implemented service running verification using ActivityManager
1. Start audio recording
2. …
=> fix: resources not cleanup properly on app kill

packages/expo-audio-ui/src/AudioVisualizer/AudioVisualizer.tsx, packages/expo-audio-ui/src/AudioVisualizer/GestureHandler.tsx
This PR refactors the AudioVisualizer component to improve logging practices and reduce unnecessary console output.
- Replaced hardcoded logger with injectable `ConsoleLike` interface
- Made logger optional and added null-safe calls
- Removed redundant console logs from GestureHandler
- Added proper typing for logger interface from expo-audio-stream
- More flexible logging configuration
- Reduced console noise in production
- Better type safety for logging calls
- No breaking changes to component API (logger is optional)
=> feat: improve audio visualizer logger handling and reduce console noise

apps/minimal/setPort.sh, apps/minimal/src/app/index.tsx, apps/playground/package.json, apps/playground/src/app/(tabs)/record.tsx, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift, packages/expo-audio-stream/ios/RecordingSettings.swift, packages/expo-audio-stream/src/useAudioRecorder.tsx, yarn.lock
This PR addresses multiple issues related to audio recording interruption handling and improves naming consistency across the codebase. It includes fixes for iOS and Android platforms, along with improvements to the minimal example app for better testing and debugging.
- Added `autoResumeAfterInterruption` flag to control automatic resume behavior after interruptions
- Fixed iOS audio session interruption handling with proper delay for resuming
- Removed unnecessary call state check in Android's resumeRecording
- Added proper event handling for call state changes when auto-resume is disabled
- Renamed `fileUri` to `compressedFileUri` in compression-related code for better clarity
- Standardized compression info structure across iOS and Android implementations
- Updated relevant type …
=> fix: improve audio recording interruption handling and consistency

documentation_site/docs/installation.md, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecordingService.kt, packages/expo-audio-stream/plugin/src/index.ts, packages/expo-audio-stream/src/useAudioRecorder.tsx
This PR addresses background recording functionality issues on both iOS and Android platforms, while also improving the status check mechanism. It includes configuration cleanup and documentation updates to better reflect the actual behavior.
- Fixed background recording behavior on Android when notifications are disabled
- Removed non-functional `keepAliveInBackground` option for iOS
- Improved status checking mechanism to prevent unnecessary checks
- Updated documentation to accurately reflect platform-specific behaviors
- Simplified configuration options and removed redundant settings
fixes #99 
fixes #100 
1. **Android Background Recording**
- Modified `AudioRecordingService` to maintain background operation based on `keepAwake` setting
- Added `getKeepAwakeStatus()` method to …
=> fix: resolve background recording issues and improve status checking

apps/playground/app.config.ts, apps/playground/src/app/_layout.tsx, packages/expo-audio-stream/android/src/main/AndroidManifest.xml, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-stream/plugin/src/index.ts, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/events.ts, packages/expo-audio-stream/src/useAudioRecorder.tsx, yarn.lock
Fixes #109, #110
This PR addresses two critical issues with Android audio recording and enhances the event handling system for recording interruptions.
- Fixes background recording stopping issue when keepAwake: true (#109)
- Prevents invalid recording resumption during phone calls (#110)
- Improves event handling for recording interruptions
- Removed the unnecessary wake lock timeout limitation
- Added proper service start when `keepAwake` is true, independent of notification settings
- Fixed `AudioRecordingService` initialization timing
- Added robust phone call state detection including VoIP calls
- Implemented prevention of recording resume during active calls
- Added detailed logging for audio states and call detection
- Fixed event subscription using correct event name …
=> fix(android): improve background recording and call interruption handling

packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift, packages/expo-audio-stream/ios/RecordingSettings.swift, packages/expo-audio-stream/src/ExpoAudioStream.types.ts
Reverts deeeed/expo-audio-stream#121
=> Revert "Add ability to separate the interval for recording and analysis"

packages/expo-audio-stream/ios/AudioStreamManager.swift, packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift, packages/expo-audio-stream/ios/RecordingSettings.swift, packages/expo-audio-stream/src/ExpoAudioStream.types.ts
Retry of #121, this time with out the CallKit code. 
Sorry for all the chaos, haven't been contributing to another repo in a while and made a few mental mistakes with the way Git works.
=> feat(ios): ability to separate the interval for recording and analysis

apps/playground/src/app/(tabs)/play.tsx, apps/playground/src/app/(tabs)/preview.tsx, apps/playground/src/app/(tabs)/record.tsx, apps/playground/src/app/_layout.tsx, apps/playground/src/component/AudioRecordingView.tsx, apps/playground/src/component/SegmentDurationSelector.tsx, apps/playground/src/component/features/FeatureViewer.tsx, apps/playground/src/component/features/SegmentAnalyzer.tsx, apps/playground/src/hooks/useAudio.tsx, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-stream/ios/AudioProcessor.swift, packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift, packages/expo-audio-stream/src/AudioAnalysis/AudioAnalysis.types.ts, packages/expo-audio-stream/src/AudioAnalysis/extractAudioAnalysis.ts, packages/expo-audio-stream/src/workers/InlineFeaturesExtractor.web.tsx, packages/expo-audio-ui/src/NavigationControls/NavigationControls.tsx
This PR improves the audio handling capabilities with enhanced trimming functionality, better waveform visualization, and more robust audio format support.
- Refactored audio trimming logic to use milliseconds consistently instead of mixing seconds/milliseconds
- Added "Restore Original" button to revert trim changes
- Improved trim preview generation with better sample rate handling
- Fixed edge cases in trim boundary calculations
- Added detailed amplitude metrics display (min/max/RMS)
- Improved segment analyzer with better metrics visualization
- Enhanced preview generation for more accurate waveform display
- Added support for normalizing audio during visualization
- Added better handling for compressed audio formats (MP3, OPUS, AAC)
- Improved metadata extraction for various audio …
=> feat(audio): improve audio trimming and waveform visualization

apps/playground/src/component/PCMPlayer.tsx, apps/playground/src/component/features/SegmentAnalyzer.tsx, apps/playground/src/hooks/useAudioSegmentData.ts, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/ExpoAudioStreamModule.ts, packages/expo-audio-stream/src/WebRecorder.web.ts
This PR introduces a new PCM player component and enhances the audio analysis capabilities across our playground application. The changes improve audio playback functionality, segment analysis, and overall audio handling infrastructure.
- Added new `PCMPlayer` component for direct PCM audio playback
- Implemented time-based and position-based audio segment extraction
- Enhanced audio analysis with configurable points per second
- Added support for web-based audio extraction and playback
- Refactored `extractAudioAnalysis` to use `extractAudioFromAnyFormat` for consistent handling
- Improved audio buffer processing with better error handling
- Added comprehensive logging throughout audio processing pipeline
- Enhanced trim functionality with change detection and preview generation
- …
=> feat(playground): add PCM player and improve audio segment analysis

packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecordingService.kt
Fixes #134: Restricted foreground service types
This PR addresses compatibility issues with Android 15's (UPSIDE_DOWN_CAKE) new restrictions on foreground services started from `BOOT_COMPLETED`. The changes ensure the audio recording service behaves correctly when started during device boot on Android 15+ devices.
Android 15 has introduced restrictions that prevent apps from starting foreground services directly from `BOOT_COMPLETED` broadcast receivers. This was causing potential crashes in our audio recording functionality when the service attempted to start on device boot.
- Added a check to detect if the service is being started from `BOOT_COMPLETED` event
- Prevented foreground service initialization specifically for boot-triggered starts on Android 15+
- Maintained existing behavior …
=> fix(android): handle foreground service restrictions for Android 15

apps/playground/src/app/(tabs)/preview.tsx, apps/playground/src/component/AudioRecordingView.tsx, apps/playground/src/component/features/SegmentAnalyzer.tsx, apps/playground/src/component/features/SpeechAnalyzer.tsx, packages/expo-audio-stream/src/AudioAnalysis/AudioAnalysis.types.ts, packages/expo-audio-stream/src/AudioAnalysis/extractAudioAnalysis.ts, packages/expo-audio-stream/src/index.ts, packages/expo-audio-ui/src/AudioVisualizer/AudioVisualizer.tsx
This PR introduces significant enhancements to the audio analysis and visualization capabilities within the `expo-audio-stream` and `expo-audio-ui` packages, along with related updates in the playground app. 
- **Improved Audio Analysis Flexibility**: Refactor `extractAudioAnalysis` to support both time-based and byte-based ranges
- **Better Visualization Control**: Add reset functionality and improve audio data handling in `AudioVisualizer`
- **Enhanced Speech Analysis**: Improve `SpeechAnalyzer` with better data validation and debug logging
- **Simplified Preview Generation**: Replace `AudioPreview` with `AudioAnalysis` for consistency
- **Code Quality**: Improve type safety, logging, and error handling across the codebase
These changes improve the developer experience by providing more …
=> feat(audio-analysis): enhance audio analysis and visualization capabilities

apps/playground/package.json, apps/playground/src/app/(tabs)/play.tsx, apps/playground/src/component/AudioRecordingView.tsx, apps/playground/src/component/HexDataViewer.tsx, apps/playground/src/component/PCMPlayer.tsx, apps/playground/src/component/features/SegmentAnalyzer.tsx, apps/playground/src/hooks/useAudioSegmentData.ts, apps/playground/src/hooks/useSileroVAD.ts, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioFormatUtils.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioProcessor.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/Features.kt, packages/expo-audio-stream/ios/AudioProcessingHelpers.swift, packages/expo-audio-stream/ios/AudioProcessor.swift, packages/expo-audio-stream/ios/DecodingConfig.swift, packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift, packages/expo-audio-stream/ios/Features.swift, packages/expo-audio-stream/package.json, packages/expo-audio-stream/src/AudioAnalysis/AudioAnalysis.types.ts, packages/expo-audio-stream/src/AudioAnalysis/extractAudioAnalysis.ts, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/ExpoAudioStreamModule.ts, packages/expo-audio-stream/src/WebRecorder.web.ts, packages/expo-audio-stream/src/utils/audioProcessing.ts, packages/expo-audio-stream/src/workers/InlineFeaturesExtractor.web.tsx, yarn.lock
This PR improves the reliability and accuracy of audio segment extraction and processing across our applications by implementing proper checksum verification using CRC32 and enhancing audio analysis capabilities. The changes standardize how audio data is extracted, processed, and verified in both native platforms and web.
* **CRC32 Checksums**: Replaced custom checksum logic with standardized CRC32 algorithm for more reliable audio data verification
* **Unified Audio Data Extraction**: Restructured the `extractAudioData` API to return consistent data structures across platforms
* **Enhanced Segment Analysis**: Improved the audio segment analyzer UI with better representation of byte ranges and checksum information
* **Audio Processing Improvements**: Fixed audio data position calculation …
=> feat(audio): enhance checksum verification and audio segment analysis

apps/playground/src/component/features/SegmentAnalyzer.tsx, apps/playground/src/component/features/SpeechAnalyzer.tsx, apps/playground/src/hooks/useSileroVAD.ts
This PR improves the Voice Activity Detection (VAD) system by implementing a multi-window analysis approach that more closely follows the Silero VAD reference implementation. The changes deliver better speech detection accuracy by analyzing audio across multiple windows while maintaining context between them.
- Refactored `useSileroVAD` hook to support windowed analysis with continuous state
- Added support for 8kHz and 16kHz sample rates (previously only 16kHz)
- Introduced `maxSpeechDuration` parameter to limit speech segment length
- Modified speech padding to match Silero's default 30ms (was 200ms)
- Restructured audio data handling to use pre-normalized audio data
- Enhanced logging with detailed probability statistics
- Changed `SpeechAnalyzer` component to accept `audioData` object …
=>  feat(audio): enhance VAD implementation with multi-window analysis

apps/playground/public/audioStorage.worker.js, apps/playground/src/app/(tabs)/files.tsx, apps/playground/src/app/(tabs)/record.tsx, apps/playground/src/context/AudioFilesProvider.tsx, apps/playground/src/utils/indexedDB.ts, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioProcessor.kt, packages/expo-audio-stream/src/AudioAnalysis/extractAudioAnalysis.ts, packages/expo-audio-stream/src/ExpoAudioStream.web.ts, packages/expo-audio-stream/src/WebRecorder.web.ts, packages/expo-audio-stream/src/useAudioRecorder.tsx, packages/expo-audio-stream/src/workers/InlineFeaturesExtractor.web.tsx, packages/expo-audio-stream/src/workers/inlineAudioWebWorker.web.tsx
This PR enhances the reliability of audio recording functionality and improves web IndexedDB data management. The changes focus on three main areas:
1. **Web IndexedDB improvements**: Added proper file deletion, error handling, and resource cleanup
2. **Audio processing optimizations**: Fixed duration calculations and data point handling
3. **Web recorder refactoring**: Improved code organization and reliability
- Added a new `fileExists` helper function in `audioStorage.worker.js` to verify file existence
- Implemented proper file deletion with verification in the Web Worker
- Enhanced error handling with more detailed error messages and proper cleanup
- Added support for gracefully handling different file extensions during deletion operations
- Fixed memory leaks by properly revoking …
=> fix: audio recording reliability improvements and web IndexedDB management

apps/playground/src/app/(tabs)/import.tsx, apps/playground/src/app/(tabs)/more.tsx, apps/playground/src/app/(tabs)/trim.tsx, apps/playground/src/app/trim.tsx, apps/playground/src/components/TrimVisualization.tsx, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioRecordingService.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioTrimmer.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/Constants.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/index.ts, packages/expo-audio-stream/src/trimAudio.ts, packages/expo-audio-ui/src/AudioTimeRangeSelector/AudioTimeRangeSelector.tsx
This PR introduces a comprehensive audio trimming feature to the application, allowing users to precisely edit audio files. The implementation includes a fully functional UI for trimming operations with multiple modes (single range, keep ranges, remove ranges), real-time visualization, and playback capability.
**Note: Currently, this feature is only available on Android and is not fully optimized for production use. Performance may vary based on file size and device capabilities.**
- **Multiple Trimming Modes**:
- **Single Range**: Extract a specific segment of audio between start and end times
- **Keep Ranges**: Select multiple segments to keep while removing everything else
- **Remove Ranges**: Select multiple segments to remove while keeping everything else
- **Output Format Options**: …
=> feat(trim): add audio trimming functionality with visualization and preview (Android only)

apps/playground/app.config.ts, apps/playground/src/app/trim.tsx, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioProcessor.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioTrimmer.kt, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-stream/src/trimAudio.ts
This pull request introduces significant improvements to the audio trimming functionality in the Expo Audio Stream module, focusing on performance optimization, better user feedback, and more efficient processing of audio ranges.
The primary goals of these changes are to:
1. Improve trimming performance by implementing more efficient audio range processing
2. Provide better user feedback with processing time information
3. Optimize resource usage by using larger buffers and smarter processing paths
4. Enhance WAV file handling with a fast-path for WAV-to-WAV trimming
These changes will result in:
- Faster audio trimming operations, especially for compressed formats
- More informative UI feedback showing processing duration
- Better memory efficiency with larger buffer sizes
- Maintained …
=> feat: Enhance audio trimming with optimized processing and detailed feedback

apps/playground/src/app/trim.tsx, packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/AudioTrimmer.kt, packages/expo-audio-stream/ios/AudioProcessor.swift, packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift, packages/expo-audio-stream/src/trimAudio.ts
This pull request enhances the audio trimming functionality across Android, iOS, and React Native layers by:
- Adding full iOS support for trimming (previously Android-only)
- Adding support for custom output filenames 
- Improving format handling consistency
- Standardizing MIME type handling across platforms
These changes improve user experience by allowing more control over output files and ensuring consistent behavior across platforms, while maintaining backwards compatibility with existing APIs.
- **Custom Filename Support**: Added `customFileName` state and UI component (`EditableInfoCard`) to allow users to specify output filenames
- **UI Improvements**: Refactored `renderStopped` for better code organization and added playback visualization for trimmed results
- **API Expansion**: …
=> feat(trim): Implement iOS trim support with custom filename and format improvements

documentation_site/docs/api-reference/api-intro.md, documentation_site/docs/api-reference/audio-features/audio-analysis-example.md, documentation_site/docs/api-reference/audio-features/audio-analysis-overview.md, documentation_site/docs/api-reference/audio-processing/extract-mel-spectrogram.md, documentation_site/docs/api-reference/audio-processing/trim-audio.md, documentation_site/docs/features.md, documentation_site/docs/ui-components.md, documentation_site/sidebars.ts, packages/expo-audio-stream/README.md, packages/expo-audio-stream/src/ExpoAudioStream.types.ts, packages/expo-audio-ui/README.md
This pull request significantly enhances the documentation for the `@siteed/expo-audio-stream` package by adding comprehensive details about audio analysis, processing capabilities, and UI components. The changes aim to improve developer experience by providing:
- Detailed documentation for new audio processing APIs (`extractMelSpectrogram`, `trimAudio`)
- Practical examples demonstrating real-world usage (`audio-analysis-example.md`)
- Updated API reference structure with clearer categories
- Documentation for the companion `@siteed/expo-audio-ui` package
- Enhanced feature lists and READMEs for better project overview
These updates make the library more accessible to developers working on audio-related features, from basic recording to advanced analysis and visualization.
1. **New …
=> feat(docs): enhance audio processing documentation and examples

apps/playground/src/app/essentia.tsx, apps/playground/src/components/MusicGenreClassifier.tsx, apps/playground/src/components/SpeechEmotionClassifier.tsx, packages/react-native-essentia/cpp/react-native-essentia.cpp, packages/react-native-essentia/src/EssentiaAPI.tsx, packages/react-native-essentia/src/index.tsx, packages/react-native-essentia/src/pipelines/musicGenreClassification.ts, packages/react-native-essentia/src/pipelines/speechEmotionRecognition.ts, packages/react-native-essentia/src/types/core.types.tsx, packages/react-native-essentia/src/types/piepleine.types.ts, packages/react-native-essentia/src/types/pipeline.types.ts
This pull request introduces significant enhancements to the `@siteed/react-native-essentia` package and its playground application by adding support for music genre classification and speech emotion recognition pipelines. These additions leverage Essentia's audio analysis capabilities to provide pre-configured feature extraction pipelines, making it easier for developers to integrate advanced audio classification into React Native applications.
- **New Functionality**: Adds two new pipeline-based features:
- **Music Genre Classification**: Extracts features like MFCC, MelBands, Spectral Centroid, Spectral Contrast, Chromagram, and ZeroCrossingRate to aid in classifying music genres.
- **Speech Emotion Recognition**: Extracts MFCC, PitchYinFFT, and RollOff features to support emotion …
=> feat: Add Music Genre and Speech Emotion Classification Pipelines to Essentia Integration

apps/playground/src/app/(tabs)/record.tsx, apps/playground/src/component/TranscriptionModeConfig.tsx, apps/playground/src/component/TranscriptionModeConfigForm.tsx, apps/playground/src/context/TranscriptionProvider.tsx, apps/playground/src/context/TranscriptionProvider.types.tsx, apps/playground/src/context/TranscriptionProvider.web.tsx, apps/playground/src/hooks/useUnifiedTranscription.ts
This PR introduces a new batch transcription mode alongside the existing live transcription feature. The batch approach processes audio at regular intervals instead of continuously, providing more stability and resource efficiency while still delivering timely results.
- **Enhanced reliability**: Reduces transcription failures by processing audio in manageable chunks
- **Platform optimizations**: Tailored implementations for web and native platforms
- **Improved UX**: Shows transcription status and intermediate results to users
- **Configurable settings**: Allows fine-tuning of transcription parameters
- Added a new batch transcription mode that:
- Collects audio for a configurable time period before processing
- Uses platform-specific optimizations (Float32Array for web, base64 for …
=> feat: implement batch transcription mode for audio records

apps/playground/package.json, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-studio/src/AudioAnalysis/extractAudioAnalysis.ts, packages/expo-audio-studio/src/workers/InlineFeaturesExtractor.web.tsx, yarn.lock
This PR improves the `expo-audio-studio` Android implementation by adding intelligent permission handling for phone state and notifications. It introduces permission detection from the app manifest to avoid requesting permissions that aren't declared, improving app store compliance and user experience.
- Added manifest-based permission detection during module initialization
- Added configurable flags `enablePhoneStateHandling` and `enableNotificationHandling` based on manifest permissions
- Modified `startRecording` to automatically disable notifications if permission is not declared
- Implemented proper permission checks for `READ_PHONE_STATE` and `POST_NOTIFICATIONS`
- Improved logging for permission status to aid debugging
- Removed `@expo/cli` dependency from playground app (unrelated …
=> feat(audio-stream): enhance Android permission handling for phone state and notifications

apps/playground/src/app/(tabs)/record.tsx, documentation_site/docs/api-reference/api-intro.md, documentation_site/docs/api-reference/recording-config.md, documentation_site/docs/features.md, documentation_site/docs/index.md, documentation_site/docs/installation.md, packages/expo-audio-studio/README.md, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/AudioRecorderManager.kt, packages/expo-audio-studio/android/src/main/java/net/siteed/audiostream/ExpoAudioStreamModule.kt, packages/expo-audio-studio/ios/AudioStreamManager.swift, packages/expo-audio-studio/ios/ExpoAudioStreamModule.swift, packages/expo-audio-studio/ios/Features.swift, packages/expo-audio-studio/src/AudioAnalysis/AudioAnalysis.types.ts, packages/expo-audio-studio/src/ExpoAudioStream.types.ts, packages/expo-audio-studio/src/ExpoAudioStream.web.ts, packages/expo-audio-studio/src/ExpoAudioStreamModule.ts, packages/expo-audio-studio/src/types/crc-32.d.ts, packages/expo-audio-studio/src/useAudioRecorder.tsx, packages/expo-audio-studio/src/utils/BlobFix.ts, yarn.lock
This pull request introduces a zero-latency audio recording feature to the `@siteed/expo-audio-studio` library via the new `prepareRecording` API. By pre-initializing audio resources, this feature eliminates startup delays, making it ideal for time-critical applications like voice command systems or musical recording tools. The update ensures consistent performance across iOS, Android, and web platforms, enhancing user experience and reliability.
The playground app has been updated to include a "Prepare Recording" button, allowing developers to validate the zero-latency feature directly.
1. **Zero-Latency Recording**:
- Added `prepareRecording` method to pre-initialize audio resources (permissions, sessions, buffers) without starting the recording.
- Implemented state tracking with an …
=> feat: Add Zero-Latency Audio Recording with `prepareRecording` API

apps/playground/package.json, apps/playground/src/app/(tabs)/record.tsx, yarn.lock
This pull request introduces an advanced mode for the recording settings in the playground app, enhancing user control over recording configurations. It also updates the `react-native-paper` dependency to version 5.14.0 and refreshes the lockfile to maintain dependency consistency.
The new advanced mode allows users to toggle between a simplified recording interface and a detailed configuration view. In basic mode, users can set a custom filename, select an audio device, and enable live transcription. In advanced mode, they gain access to additional settings like recording configuration and transcription options, providing greater flexibility for power users. This improves the user experience by catering to both novice and advanced users.
The update to `react-native-paper` ensures …
=> feat(playground): add advanced mode for recording settings

apps/playground/PUBLISH_STORE.md, apps/playground/app.config.ts, apps/playground/package.json, apps/playground/src/app/(tabs)/more.tsx, apps/playground/src/app/_layout.tsx, apps/playground/src/component/BackgroundUpdater.tsx, apps/playground/src/component/Updater.tsx, apps/playground/src/hooks/useAppUpdates.ts, scripts/update-runtime-version.js, yarn.lock
This pull request improves the Over-The-Air (OTA) update system for the playground app by adding background update checks and streamlining update management.
- **Background Updates**: Enables automatic update checks when the app is backgrounded, ensuring users receive updates seamlessly.
- **Improved Update Controls**: Adds UI for toggling automatic updates and viewing update details.
- **Automated Versioning**: Introduces scripts to sync `runtimeVersion` with `package.json` version and update `CHANGELOG.md`.
- **Better Documentation**: Updates `PUBLISH_STORE.md` with clear OTA update guidelines.
=> feat(playground): enhance OTA updates with background update functionality

apps/playground/app.config.ts, documentation_site/docs/api-reference/recording-config.md, packages/expo-audio-studio/ios/AudioProcessor.swift, packages/expo-audio-studio/ios/AudioStreamManager.swift, packages/expo-audio-studio/plugin/src/index.ts
This PR fixes issues with iOS background audio recording and improves audio format conversion in `expo-audio-studio`. It ensures reliable recording in the background and robust error handling during audio processing, with updated documentation.
- Fixes iOS background recording to prevent interruptions.
- Improves audio format conversion reliability.
- Clarifies setup in documentation for better developer experience.
- Enabled `useAudio: true` in `app.config.ts` for iOS background recording.
- Updated `AudioStreamManager.swift` to manage audio sessions with `.playAndRecord`, `.mixWithOthers`, and `.duckOthers`.
- Enhanced `AudioProcessor.swift` with better error handling for format conversion.
- Added `audio` background mode to `Info.plist` via plugin (`index.ts`).
- Updated …
=> fix: Enhance iOS Background Audio Recording and Audio Format Conversion

apps/playground/CHANGELOG.md, apps/playground/CONTRIBUTE-playground.md, apps/playground/app.config.ts, apps/playground/package.json, apps/playground/src/app/(tabs)/files.tsx, apps/playground/src/app/(tabs)/import.tsx, apps/playground/src/app/(tabs)/more.tsx, apps/playground/src/app/(tabs)/record.tsx, apps/playground/src/app/_layout.tsx, apps/playground/src/components/WebAppBanner.tsx, apps/playground/src/hooks/useAppUpdates.ts, apps/playground/src/hooks/useAudio.tsx, apps/sherpa-onnx-demo/src/app/(tabs)/index.tsx, packages/expo-audio-studio/ios/AudioNotificationManager.swift, packages/expo-audio-studio/ios/AudioProcessingHelpers.swift, packages/expo-audio-studio/ios/AudioProcessor.swift, packages/expo-audio-studio/ios/AudioStreamManager.swift, packages/expo-audio-studio/ios/DataPoint.swift, packages/expo-audio-studio/ios/ExpoAudioStreamModule.swift, packages/playgroundapi/ios/PlaygroundAPIModule.swift, yarn.lock
This pull request introduces version 1.0.1 of the Audio Playground, enhancing audio processing stability, simplifying app update handling, improving navigation consistency, and adding debugging documentation. The changes aim to improve user experience, maintainability, and developer productivity.
- **Audio Stability**: Improved thread safety and resource management in `AudioNotificationManager` and `AudioStreamManager`, ensuring reliable background audio recording and format conversion.
- **App Updates**: Simplified update handling by enabling automatic updates on app load and removing manual update toggles, streamlining the user experience.
- **Navigation Consistency**: Refactored navigation to use `router.navigate` instead of `router.push`, aligning with modern navigation practices for …
=> feat(playground): Version 1.0.1 with Audio Enhancements, App Updates, and Navigation Refactor

packages/expo-audio-studio/ios/AudioStreamManager.swift
- Fixes #257 - Audio streaming now works correctly when `output.primary.enabled = false` on iOS
- Ensures platform consistency across iOS, Android, and Web
On iOS, when file writing was disabled (`output.primary.enabled = false`), the `onAudioStream` callback was never called. This prevented audio streaming use cases where file storage isn't needed.
The tap block in `installTapWithHardwareFormat` was checking for `recordingFileURL` existence:
```swift
guard let self = self,
let fileURL = self.recordingFileURL,  // This fails when primary output is disabled\!
self.isRecording else {
return
}
```
Since `recordingFileURL` is nil when primary output is disabled, the guard failed and `processAudioBuffer` was never called, blocking all audio streaming.
1. Removed the unnecessary …
=> fix(expo-audio-studio): enable audio streaming when primary output is disabled on iOS
